robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Velocity Controllers ---------------------------------------
  camera_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: camera_joint
    pid: 
      p: 1.0
      i: 0.0
      d: 0.0 